<#
.SYNOPSIS
    Transfers files from source OneDrive to destination OneDrive using the manifest
    generated by Lab Script 4.

.DESCRIPTION
    Lab Script 5 of 8 — StoneZone Security M365 Migration Script Library
    Companion to: Mastering Microsoft 365 Migrations by Sterling Stone

    Reads the file manifest CSV, downloads each file to a local temp location, then
    uploads it to the destination OneDrive. Files under 4 MB use single-request upload.
    Files 4 MB and larger use the Graph upload session API to handle chunked transfer.

    Failed transfers are logged and written to an error CSV for retry.

.PARAMETER ManifestPath
    Path to the file manifest CSV generated by Lab Script 4.
    If omitted, uses the path stored in $global:ManifestPath from Script 4.

.PARAMETER ChunkSizeMB
    Chunk size in MB for large-file upload sessions. Must be a multiple of 320 KB.
    Default: 10 MB (10485760 bytes).

.PARAMETER MaxRetries
    Number of retry attempts for failed transfers. Default: 3.

.NOTES
    Required Graph Scopes (destination app): Files.ReadWrite.All
    Run Lab Script 1 to establish connections. Run Script 4 to generate the manifest.
    Download URLs in the manifest expire after ~60 minutes — re-run Script 4 if stale.

    Author:  Sterling Stone — StoneZone Security LLC
    Version: 1.0.0
    Updated: 2026-04
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [string]$ManifestPath = "",
    [int]$ChunkSizeMB = 10,
    [int]$MaxRetries  = 3
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'

#region ── Logging ────────────────────────────────────────────────────────────
$Timestamp  = Get-Date -Format 'yyyyMMdd-HHmmss'
$LogFile    = "$global:LogRoot\TransferFiles-$Timestamp.log"
$ErrorCsv   = "$global:DataRoot\TransferFiles-Errors-$Timestamp.csv"
$ResultsCsv = "$global:DataRoot\TransferFiles-Results-$Timestamp.csv"

function Write-Log {
    param([string]$Message, [string]$Level = 'INFO')
    $entry = "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [$Level] $Message"
    Add-Content -Path $LogFile -Value $entry
    $color = switch ($Level) { 'WARN' {'Yellow'} 'ERROR' {'Red'} default {'Cyan'} }
    Write-Host $entry -ForegroundColor $color
}
#endregion

#region ── Resolve manifest path ─────────────────────────────────────────────
if (-not $ManifestPath) {
    if ($global:ManifestPath) {
        $ManifestPath = $global:ManifestPath
    } else {
        throw "ManifestPath not specified and `$global:ManifestPath not set. Run Script 4 first."
    }
}
if (-not (Test-Path $ManifestPath)) { throw "Manifest not found: $ManifestPath" }
if (-not $global:DestContext) { throw "Destination context not found. Run Script 1 first." }
#endregion

$manifest   = Import-Csv -Path $ManifestPath
$chunkBytes = $ChunkSizeMB * 1MB
$results    = [System.Collections.Generic.List[PSObject]]::new()
$errors     = [System.Collections.Generic.List[PSObject]]::new()
$transferred = 0; $failed = 0; $skipped = 0

Write-Log "Starting transfer of $($manifest.Count) files from manifest: $ManifestPath"

foreach ($file in $manifest) {
    # Sanitise path — remove leading slash, replace backslashes
    $cleanPath = $file.FilePath.TrimStart('/').Replace('\','/')
    $tmpFile   = [System.IO.Path]::GetTempFileName()
    $attempt   = 0
    $success   = $false

    while ($attempt -lt $MaxRetries -and -not $success) {
        $attempt++
        try {
            # Download from source
            Invoke-WebRequest -Uri $file.DownloadUrl -OutFile $tmpFile -UseBasicParsing

            if ($PSCmdlet.ShouldProcess($file.UserUPN, "Upload $cleanPath")) {
                $sizeBytes = [long]$file.SizeBytes

                if ($sizeBytes -lt 4MB) {
                    #── Small file: single PUT ────────────────────────────────
                    $uploadUrl = "https://graph.microsoft.com/v1.0/users/$($file.UserUPN)/drive/root:/$($cleanPath):/content"
                    $headers   = @{ Authorization = "Bearer $((Get-MgContext).AccessToken)" }
                    Invoke-RestMethod -Uri $uploadUrl -Method PUT `
                        -InFile $tmpFile -ContentType 'application/octet-stream' `
                        -Headers $headers | Out-Null

                } else {
                    #── Large file: upload session ────────────────────────────
                    $sessionUrl = "https://graph.microsoft.com/v1.0/users/$($file.UserUPN)/drive/root:/$($cleanPath):/createUploadSession"
                    $headers    = @{ Authorization = "Bearer $((Get-MgContext).AccessToken)" }
                    $uploadBody = [System.Text.Encoding]::UTF8.GetBytes('{"item":{"conflictBehavior":"replace"}}')
                    $session    = Invoke-RestMethod -Uri $sessionUrl -Method POST `
                                    -Headers $headers -ContentType 'application/json' `
                                    -Body $uploadBody

                    $stream     = [System.IO.File]::OpenRead($tmpFile)
                    $buffer     = New-Object byte[] $chunkBytes
                    $offset     = 0

                    try {
                        while ($offset -lt $sizeBytes) {
                            $read  = $stream.Read($buffer, 0, $chunkBytes)
                            $chunk = $buffer[0..($read-1)]
                            $end   = $offset + $read - 1
                            $rangeHeaders = @{
                                'Content-Range'  = "bytes $offset-$end/$sizeBytes"
                                'Content-Length' = $read
                                'Authorization'  = "Bearer $((Get-MgContext).AccessToken)"
                            }
                            Invoke-RestMethod -Uri $session.uploadUrl -Method PUT `
                                -Body $chunk -Headers $rangeHeaders | Out-Null
                            $offset += $read
                        }
                    } finally {
                        $stream.Close()
                    }
                }

                $success = $true
                $transferred++
                Write-Log "  OK [$attempt]: $($file.UserUPN) | $cleanPath ($([math]::Round($sizeBytes/1KB,1)) KB)"
                $results.Add([PSCustomObject]@{
                    UserUPN   = $file.UserUPN
                    FilePath  = $cleanPath
                    SizeBytes = $sizeBytes
                    Status    = 'Transferred'
                    Attempts  = $attempt
                    Timestamp = (Get-Date -Format 'o')
                })
            }

        } catch {
            Write-Log "  Attempt $attempt failed: $($file.UserUPN) | $cleanPath — $_" 'WARN'
            Start-Sleep -Seconds (2 * $attempt)   # Back off on retry
        } finally {
            if (Test-Path $tmpFile) { Remove-Item $tmpFile -Force -ErrorAction SilentlyContinue }
        }
    }

    if (-not $success) {
        $failed++
        Write-Log "  FAILED after $MaxRetries attempts: $cleanPath" 'ERROR'
        $errors.Add([PSCustomObject]@{
            UserUPN   = $file.UserUPN
            FilePath  = $cleanPath
            SizeBytes = $file.SizeBytes
            Error     = "Failed after $MaxRetries attempts"
            Timestamp = (Get-Date -Format 'o')
        })
    }
}

$results | Export-Csv -Path $ResultsCsv -NoTypeInformation
if ($errors.Count -gt 0) {
    $errors | Export-Csv -Path $ErrorCsv -NoTypeInformation
    Write-Log "Error log: $ErrorCsv" 'WARN'
}
Write-Log "Transfer complete. Succeeded: $transferred | Failed: $failed"
